//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Juno.OnPrem.Auth.SPTokenChange.Layouts.Juno.OnPrem.Auth.SPTokenChange
{


    public partial class ConfigCache
    {
    }
}
